#!/usr/bin/env python3
"""
Report Schema
=============
Typed data contracts for the AI-generated coaching report.

Every module that produces or consumes coaching feedback
must use these types — never raw dicts or untyped strings.

Maps to the aiFeedback + drills fields of FootballSession in types.ts.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional

from schemas.player_schema   import SkillLevel
from schemas.activity_schema import FootballAction


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class IssueSeverity(str, Enum):
    HIGH   = "high"
    MEDIUM = "medium"
    LOW    = "low"


class ReportSource(str, Enum):
    LLM      = "llm"       # generated by the LLM via ExplanationEngine
    RULE     = "rule"      # generated by feedback_engine.py rule system
    FALLBACK = "fallback"  # offline/template fallback


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------

@dataclass
class CoachingIssue:
    """
    A single identified performance problem with severity and plain-English explanation.
    """
    metric:      str                   # e.g. "torso_lean"
    observation: str                   # plain English — what was observed
    severity:    IssueSeverity         = IssueSeverity.MEDIUM

    def to_dict(self) -> dict:
        return {
            "metric":      self.metric,
            "observation": self.observation,
            "severity":    self.severity.value,
        }


@dataclass
class DrillReport:
    """
    A single training drill targeting a specific metric.
    """
    name:          str
    target_metric: str
    instructions:  str
    coach_tip:     str
    duration:      str              # e.g. "10 min"
    difficulty:    SkillLevel       = SkillLevel.BEGINNER

    def to_dict(self) -> dict:
        return {
            "name":         self.name,
            "targetMetric": self.target_metric,
            "instructions": self.instructions,
            "coachTip":     self.coach_tip,
            "duration":     self.duration,
            "difficulty":   self.difficulty.value,
        }


@dataclass
class CoachingReport:
    """
    Full AI-generated coaching report for one session.

    Produced by ai/explanation_engine.py (LLM path)
    or feedback_engine.py (rule-based path).

    Maps to the aiFeedback + drills fields of FootballSession.
    """

    # Five mandatory sections
    summary:          str
    strengths:        List[str]           = field(default_factory=list)
    issues:           List[CoachingIssue] = field(default_factory=list)
    drills:           List[DrillReport]   = field(default_factory=list)
    coach_tip:        str                 = ""
    motivational_tip: str                 = ""

    # Context
    player_level:     SkillLevel          = SkillLevel.BEGINNER
    primary_activity: Optional[str]       = None

    # Metadata
    source:           ReportSource        = ReportSource.RULE
    llm_provider:     Optional[str]       = None
    llm_model:        Optional[str]       = None
    latency_s:        float               = 0.0
    from_fallback:    bool                = False

    # ------------------------------------------------------------------
    # Convenience
    # ------------------------------------------------------------------

    @property
    def weakness_labels(self) -> List[str]:
        """Flat list of weak metric labels — used by the frontend."""
        return [i.metric.replace("_", " ").title() for i in self.issues]

    @property
    def coaching_tips(self) -> List[str]:
        """Coach tips from each drill — used in aiFeedback.coachingTips."""
        return [d.coach_tip for d in self.drills]

    @property
    def priority_drill(self) -> Optional[DrillReport]:
        """First (highest priority) drill."""
        return self.drills[0] if self.drills else None

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def to_ai_feedback_dict(self) -> dict:
        """
        Return the aiFeedback shape expected by types.ts / FootballSession.
        """
        return {
            "summary":         self.summary,
            "strengths":       self.strengths,
            "weaknesses":      self.weakness_labels,
            "coachingTips":    self.coaching_tips,
            "motivationalTip": self.motivational_tip or self.coach_tip,
        }

    def to_drills_list(self) -> List[dict]:
        """Return the drills list expected by types.ts / FootballSession."""
        return [d.to_dict() for d in self.drills]

    def to_dict(self) -> dict:
        """Full serialisation including metadata."""
        return {
            "summary":          self.summary,
            "strengths":        self.strengths,
            "issues":           [i.to_dict() for i in self.issues],
            "drills":           self.to_drills_list(),
            "coachTip":         self.coach_tip,
            "motivationalTip":  self.motivational_tip,
            "playerLevel":      self.player_level.value,
            "primaryActivity":  self.primary_activity,
            "_meta": {
                "source":      self.source.value,
                "llmProvider": self.llm_provider,
                "llmModel":    self.llm_model,
                "latencyS":    round(self.latency_s, 3),
                "fromFallback": self.from_fallback,
            },
        }


# ---------------------------------------------------------------------------
# Session report summary  (lightweight version for dashboard/history)
# ---------------------------------------------------------------------------

@dataclass
class SessionSummary:
    """
    Compact summary of a completed session — used in the dashboard
    history list, not the full analysis view.
    """
    session_id:          str
    file_name:           str
    player_level:        SkillLevel
    primary_activity:    Optional[str]
    overall_score:       float              # 0.0 – 1.0
    issue_count:         int
    top_strength:        Optional[str]
    top_weakness:        Optional[str]
    created_at:          str                # ISO timestamp

    def to_dict(self) -> dict:
        return {
            "sessionId":       self.session_id,
            "fileName":        self.file_name,
            "playerLevel":     self.player_level.value,
            "primaryActivity": self.primary_activity,
            "overallScore":    round(self.overall_score, 3),
            "issueCount":      self.issue_count,
            "topStrength":     self.top_strength,
            "topWeakness":     self.top_weakness,
            "createdAt":       self.created_at,
        }
